# Generated by Django 4.2.6 on 2023-11-29 20:17

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=50, null=True, verbose_name='Dia_clase')),
                ('fecha', models.DateField(verbose_name='fecha_clase')),
                ('hora', models.TimeField(blank=True, null=True, verbose_name='hora_clase')),
            ],
        ),
        migrations.CreateModel(
            name='Rutina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='nombre_rutina')),
                ('ejercicios', ckeditor.fields.RichTextField()),
            ],
            options={
                'verbose_name': 'Dia',
                'verbose_name_plural': 'rutinas de clases',
            },
        ),
    ]
