# Generated by Django 4.2.6 on 2023-11-29 20:17

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dietas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=50, null=True, verbose_name='nombre_dieta')),
                ('fecha', models.DateField(auto_now_add=True, null=True, verbose_name='fecha_dieta')),
                ('resumen', ckeditor.fields.RichTextField(blank=True, null=True)),
            ],
        ),
    ]
