# Generated by Django 4.2.6 on 2023-11-29 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('nombres', models.CharField(blank=True, max_length=30)),
                ('apellidos', models.CharField(blank=True, max_length=100)),
                ('genero', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1)),
                ('edad', models.PositiveIntegerField(default=0, null=True)),
                ('talla', models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Ingresar talla en metros', max_digits=5, null=True)),
                ('celular', models.CharField(blank=True, max_length=9, verbose_name='celular_alumno')),
                ('celular2', models.CharField(blank=True, max_length=9, verbose_name='celular_alumno2')),
                ('direccion', models.CharField(blank=True, max_length=150, verbose_name='direccion_alumno')),
                ('redsocial', models.CharField(blank=True, max_length=60, null=True, verbose_name='red_social')),
                ('fechainicio', models.DateField(auto_now_add=True, verbose_name='fecha_inicio_alumno')),
                ('fechafin', models.DateField(blank=True, null=True, verbose_name='fecha_fin_alumno')),
                ('plan', models.CharField(blank=True, choices=[('0', 'Powerlifter'), ('1', 'Disminución de grasa'), ('2', 'Aumento de peso'), ('3', 'Estetico'), ('4', 'Calistenia'), ('5', 'Personalizado')], max_length=2, verbose_name='plan_alumno')),
                ('is_staff', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_user', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
